# Site settings
title: Omar Report
email: omar@omar.report
description: what's up internet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omar.report" # the base hostname & protocol for your site
twitter_username: omarqazi
github_username:  omarqazi

# Build settings
markdown: kramdown
